contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
baseurl = "http://bruckner.danieldurante.com/"
languageCode = "en-us"
canonifyurls = true
title = "James Bruckner Hope Fund"
subtitle = "For Learning Disabled Adults"

[params]
  title = "James Bruckner Hope Fund"
  subtitle = "For Learning Disabled Adults"

[params.inc]
  title = "James Bruckner Hope Fund"
  subtitle = "For Learning Disabled Adults"
  company = "James Bruckner Hope Fund for Learning Disabled Adults"
